[2024-09-12T08:20:58.766+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T08:20:58.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: max_min_dag.generate_random_numbers scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-12T08:20:58.850+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: max_min_dag.generate_random_numbers scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-12T08:20:58.852+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-09-12T08:20:58.889+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_random_numbers> on 2024-09-11 00:00:00+00:00
[2024-09-12T08:20:58.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-12T08:20:58.906+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2024-09-12T08:20:58.906+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'max_min_dag', 'generate_random_numbers', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/tmp/tmpga0vx00o']
[2024-09-12T08:20:58.908+0000] {standard_task_runner.py:105} INFO - Job 311: Subtask generate_random_numbers
[2024-09-12T08:20:59.064+0000] {task_command.py:467} INFO - Running <TaskInstance: max_min_dag.generate_random_numbers scheduled__2024-09-11T00:00:00+00:00 [running]> on host 2d1ccf336ee9
[2024-09-12T08:20:59.294+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Denis' AIRFLOW_CTX_DAG_ID='max_min_dag' AIRFLOW_CTX_TASK_ID='generate_random_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-12T08:20:59.297+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T08:20:59.427+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T08:20:59.465+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T08:20:59.467+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=max_min_dag, task_id=generate_random_numbers, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240912T082058, end_date=20240912T082059
[2024-09-12T08:20:59.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T08:20:59.691+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-12T08:20:59.706+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
